
public enum LiveTimingMessage {
    case fullSnapshot(Envelope)
    case heartbeat(Heartbeat)
    case sessionInfo(SessionInfo)
    case timingData(TimingData)
    case timingAppData(TimingAppData)
    case timingStats(TimingStats)
    case driverList(DriverList)
    case carData(CarData)
    case carDataZ(CarData)
    case position(PositionData)
    case positionZ(PositionZ)
    case weather(WeatherData)
    case lapCount(LapCount)
    case raceControlMessages(RaceControlMessages)
    case teamRadio(TeamRadio)
    case tyreStintSeries(TyreStintSeries)
    case trackStatus(TrackStatus)
    case topThree(TopThree)
    case sessionData(SessionData)
    case extrapolatedClock(ExtrapolatedClock)
    case championshipPrediction(ChampionshipPrediction)
    case pitStopSeries(PitStopSeries)
    case pitLaneTimeCollection(PitLaneTimeCollection)
    case raw(String)
}
